name: build language

on:
  workflow_call:
    inputs:
      language:
        description: 'any of Chinese German English French Polish Italian Dutch Russian'
        required: true
        default: 'English'
        type: string
      continue-on-error:
        description: 'allows a language to fail, used when building all languages'
        required: false
        default: false
        type: boolean

jobs:
  compile:
    runs-on: windows-latest # required for msbuild
    continue-on-error: ${{ inputs.continue-on-error }}
    strategy:
      fail-fast: false
      matrix:
        application: [ja2, ja2mapeditor, ja2ub, ja2ubmapeditor]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download versions.env
        uses: actions/download-artifact@v4
        with:
          name: versions.env
          path: artifacts
      - name: Restore versions.env
        shell: bash
        run: cat artifacts/versions.env >> $GITHUB_ENV

      # TODO: Move this into CMake, just taking the GitHub Actions parameters as -D variables
      - name: Update GameVersion.cpp
        shell: bash
        run: |
          set -eux
          INPUTS_LANGUAGE=${{ inputs.language }}
          GAME_VERSION=$(echo "$GAME_VERSION" | tr -cd '[:print:]' | tr -d '"\\')
          GAME_BUILD="${INPUTS_LANGUAGE:0:2} $GAME_BUILD_INFORMATION"
          GAME_BUILD=$(echo "$GAME_BUILD" | tr -cd '[:print:]' | tr -d '"\\')
          sed -i "s|@Version@|${GAME_VERSION:0:15}|" Ja2/GameVersion.cpp
          sed -i "s|@Build@|${GAME_BUILD:0:255}|" Ja2/GameVersion.cpp
          cat Ja2/GameVersion.cpp

      - name: Prepare build properties
        shell: bash
        run: |
          set -eux

          touch CMakePresets.json

          JA2Language=$(echo '${{ inputs.language }}' | tr '[:lower:]' '[:upper:]')
          JA2Application=$(echo '${{ matrix.application }}' | tr '[:lower:]' '[:upper:]')

          echo "
          JA2Language=$JA2Language
          JA2Application=$JA2Application
          " >> $GITHUB_ENV

      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Prepare build
        run: |
          cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLanguages="$Env:JA2Language" -DApplications="$Env:JA2Application"
      - name: Build
        run: |
          cmake --build build/ -- -v
      - name: List build artifacts
        shell: bash
        run: |
          find build/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.language }}_${{ matrix.application }}
          path: build/*.exe
